name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.build-and-push.outputs.tags }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files in repository (Debugging)
      run: ls -la  # This will list all files in the repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile  # Explicitly specify the path to the Dockerfile
        tags: |
          vibhav70/trainease:${{ github.sha }}
          vibhav70/trainease:latest
        push: ${{ github.ref == 'refs/heads/main' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only deploy on main branch

    steps:
    - name: Update Render Service Image
      run: |
        curl -X PATCH \
          "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "image": "vibhav70/trainease:${{ needs.build.outputs.image-tag }}"
          }'

    - name: Trigger Render Deployment
      run: |
        curl -X POST \
          "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}'